### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gustavo23pg** [skmedix/SKlauncher#158]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 30/01/19 18:01
Description: Initializing game

java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL
at cgd.b(SourceFile:218)
at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
at org.lwjgl.system.JNI.invokePPPP(Native Method)
at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1649)
at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1827)
at cgd.<init>(SourceFile:99)
at cgc.a(SourceFile:79)
at cft.am(SourceFile:439)
at cft.a(SourceFile:380)
at net.minecraft.client.main.Main.main(SourceFile:144)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
at cgd.b(SourceFile:218)
at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
at org.lwjgl.system.JNI.invokePPPP(Native Method)
at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1649)
at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1827)
at cgd.<init>(SourceFile:99)
at cgc.a(SourceFile:79)
at cft.am(SourceFile:439)

-- Initialization --
Details:
Stacktrace:
at cft.a(SourceFile:380)
at net.minecraft.client.main.Main.main(SourceFile:144)

-- System Details --
Details:
Minecraft Version: 1.13.2
Operating System: Windows 10 (x86) version 10.0
Java Version: 1.8.0_181, Oracle Corporation
Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
Memory: 42880760 bytes (40 MB) / 202108928 bytes (192 MB) up to 523501568 bytes (499 MB)
JVM Flags: 7 total; -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
Launched Version: 1.13.2
LWJGL: 3.1.6 build 14
OpenGL: NO CONTEXT
GL Caps: 
Using VBOs: Yes
Is Modded: Probably not. Jar signature remains and client brand is untouched.
Type: Client (map_client.txt)
Resource Packs: 
Current Language: ~~ERROR~~ NullPointerException: null
Profiler "white-space:pre;">CPU: <unknown>

**Comment by skmedix** [comment]
Not related to launcher.
