### ISSUE TITLE
Bug Report - Can't Launch The Game (possible java issue)

### ISSUE THREAD

**Issue by zexion665** [skmedix/SKlauncher#165]
I completely don't know what should I do, I've updated java, I've reinstalled it, nothing helps.

[20:15:23 INFO]: Half command: C:\Program Files (x86)\Java\jre1.8.0_73\bin\javaw.exe -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx1024m -javaagent:C:\Users\Dominik\AppData\Roaming\.minecraft\sklauncher-fx.jar -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Djava.library.path=C:\Users\Dominik\AppData\Roaming\.minecraft\versions\1.14.3\1.14.3-natives-359420739829109 -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=3.0-57fe8ca -cp C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\com\mojang\patchy\1.1\patchy-1.1.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\com\mojang\javabridge\1.0.22\javabridge-1.0.22.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\21.0\guava-21.0.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\com\mojang\brigadier\1.0.17\brigadier-1.0.17.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\com\mojang\datafixerupper\2.0.24\datafixerupper-2.0.24.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\8.2.1\fastutil-8.2.1.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.14.17\realms-1.14.17.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\libraries\com\mojang\text2speech\1.11.3\text2speech-1.11.3.jar;C:\Users\Dominik\AppData\Roaming\.minecraft\versions\1.14.3\1.14.3.jar net.minecraft.client.main.Main
[20:15:23 ERROR]: Couldn't launch game
java.io.IOException: Cannot run program "C:\Program Files (x86)\Java\jre1.8.0_73\bin\javaw.exe" (in directory "C:\Users\Dominik\AppData\Roaming\.minecraft"): CreateProcess error=2, Nie można odnaleźć określonego pliku
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:1.8.0_211]
	at com.mojang.launcher.game.process.direct.DirectGameProcessFactory.startGame(DirectGameProcessFactory.java:14) ~[sklauncher-fx.jar:3.0-57fe8ca]
	at net.minecraft.launcher.game.MinecraftGameRunner.launchGame(MinecraftGameRunner.java:230) ~[sklauncher-fx.jar:3.0-57fe8ca]
	at com.mojang.launcher.game.runner.AbstractGameRunner.onDownloadJobFinished(AbstractGameRunner.java:191) ~[sklauncher-fx.jar:3.0-57fe8ca]
	at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:120) ~[sklauncher-fx.jar:3.0-57fe8ca]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.io.IOException: CreateProcess error=2, Nie można odnaleźć określonego pliku
	at java.lang.ProcessImpl.create(Native Method) ~[?:1.8.0_211]
	at java.lang.ProcessImpl.<init>(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ProcessImpl.start(Unknown Source) ~[?:1.8.0_211]
	... 10 more
[20:15:23 INFO]: Deleting C:\Users\Dominik\AppData\Roaming\.minecraft\versions\1.14.3\1.14.3-natives-359420739829109

**Comment by skmedix** [comment]
Edit your profile Game Directory from:
`C:\Users\Dominik\AppData\Roaming.minecraft\`
to
`C:\Users\Dominik\AppData\Roaming\.minecraft\`

**Comment by zexion665** [comment]
But how? It creates in the moment I launch the game and also deletes it after failing to launch. Even in the game profile setting in the launcher itself, I have it written just like you sent me.

**Comment by Valorel1982** [comment]
i have a issue like that, this is the report file the louncher give me:
PC:
Core I5 2400 3.1GHZ
8GB RAM
Geforce 405 1GB

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 09/07/19 06:54 PM
Description: mouseClicked event handler

java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at vz.f(SourceFile:55)
	at zs.a(SourceFile:16)
	at vz.a(SourceFile:136)
	at cvo.a(SourceFile:1640)
	at ddg$a.e(SourceFile:380)
	at ddg$a.a(SourceFile:311)
	at ddg$a.mouseClicked(SourceFile:252)
	at cwq.mouseClicked(SourceFile:322)
	at cxp.mouseClicked(SourceFile:27)
	at cvp.b(SourceFile:86)
	at czx.wrapScreenError(SourceFile:441)
	at cvp.a(SourceFile:86)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at cuh.l(SourceFile:425)
	at cuh.c(SourceFile:283)
	at cvo.b(SourceFile:1023)
	at cvo.e(SourceFile:976)
	at cvo.b(SourceFile:411)
	at net.minecraft.client.main.Main.main(SourceFile:154)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:177)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:151)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 27 more
Caused by: java.io.IOException: Unable to establish loopback connection
	at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
	at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.ch.PipeImpl.<init>(Unknown Source)
	at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source)
	at java.nio.channels.Pipe.open(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source)
	at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
	... 31 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Unknown Source)
	at sun.nio.ch.Net.connect(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
	at java.nio.channels.SocketChannel.open(Unknown Source)
	at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(Unknown Source)
	... 40 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at vz.f(SourceFile:55)
	at zs.a(SourceFile:16)
	at vz.a(SourceFile:136)
	at cvo.a(SourceFile:1640)
	at ddg$a.e(SourceFile:380)
	at ddg$a.a(SourceFile:311)
	at ddg$a.mouseClicked(SourceFile:252)
	at cwq.mouseClicked(SourceFile:322)
	at cxp.mouseClicked(SourceFile:27)
	at cvp.b(SourceFile:86)

-- Affected screen --
Details:
	Screen name: ddf
Stacktrace:
	at czx.wrapScreenError(SourceFile:441)
	at cvp.a(SourceFile:86)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at cuh.l(SourceFile:425)
	at cuh.c(SourceFile:283)
	at cvo.b(SourceFile:1023)
	at cvo.e(SourceFile:976)
	at cvo.b(SourceFile:411)
	at net.minecraft.client.main.Main.main(SourceFile:154)

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 943146016 bytes (899 MB) / 1811939328 bytes (1728 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: 1.14.3
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce 405/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: EspaÃ±ol (Venezuela)
	CPU: 4x Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz

Thankz in advance!

**Comment by D34D-514R** [comment]
@zexion665 | This is how to change game directory in SKLauncher:

![howtochangegamedirectory](https://user-images.githubusercontent.com/39349444/68494473-c8ee8180-024e-11ea-80bf-6734a4207b0f.gif)
