### ISSUE TITLE
Issue to load world affter lounch

### ISSUE THREAD

**Issue by Valorel1982** [skmedix/SKlauncher#169]
i have the next issue affter l try to enter my world:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 09/07/19 06:54 PM
Description: mouseClicked event handler

java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at vz.f(SourceFile:55)
	at zs.a(SourceFile:16)
	at vz.a(SourceFile:136)
	at cvo.a(SourceFile:1640)
	at ddg$a.e(SourceFile:380)
	at ddg$a.a(SourceFile:311)
	at ddg$a.mouseClicked(SourceFile:252)
	at cwq.mouseClicked(SourceFile:322)
	at cxp.mouseClicked(SourceFile:27)
	at cvp.b(SourceFile:86)
	at czx.wrapScreenError(SourceFile:441)
	at cvp.a(SourceFile:86)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at cuh.l(SourceFile:425)
	at cuh.c(SourceFile:283)
	at cvo.b(SourceFile:1023)
	at cvo.e(SourceFile:976)
	at cvo.b(SourceFile:411)
	at net.minecraft.client.main.Main.main(SourceFile:154)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:177)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:151)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 27 more
Caused by: java.io.IOException: Unable to establish loopback connection
	at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
	at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.ch.PipeImpl.<init>(Unknown Source)
	at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source)
	at java.nio.channels.Pipe.open(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source)
	at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
	... 31 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Unknown Source)
	at sun.nio.ch.Net.connect(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
	at java.nio.channels.SocketChannel.open(Unknown Source)
	at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(Unknown Source)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at vz.f(SourceFile:55)
	at zs.a(SourceFile:16)
	at vz.a(SourceFile:136)
	at cvo.a(SourceFile:1640)
	at ddg$a.e(SourceFile:380)
	at ddg$a.a(SourceFile:311)
	at ddg$a.mouseClicked(SourceFile:252)
	at cwq.mouseClicked(SourceFile:322)
	at cxp.mouseClicked(SourceFile:27)
	at cvp.b(SourceFile:86)

-- Affected screen --
Details:
	Screen name: ddf
Stacktrace:
	at czx.wrapScreenError(SourceFile:441)
	at cvp.a(SourceFile:86)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at cuh.l(SourceFile:425)
	at cuh.c(SourceFile:283)
	at cvo.b(SourceFile:1023)
	at cvo.e(SourceFile:976)
	at cvo.b(SourceFile:411)
	at net.minecraft.client.main.Main.main(SourceFile:154)

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 943146016 bytes (899 MB) / 1811939328 bytes (1728 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: 1.14.3
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce 405/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: EspaÃ±ol (Venezuela)
	CPU: 4x Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz

I realy apretiate the help you can give me!

**Comment by skmedix** [comment]
Not related to launcher.
https://bugs.mojang.com/browse/MC-34749

**Comment by skmedix** [comment]
**Note:** I'll add java arg `-Djava.net.preferIPv4Stack=true` by default in next update

[ ] - Is update released

**Comment by skmedix** [comment]
Please, restart launcher and try again

**Comment by Valorel1982** [comment]
ty!
