### ISSUE TITLE
error when wanting to start the minecraft

### ISSUE THREAD

**Issue by agus98698** [skmedix/SKlauncher#195]
Hi there! When I want to play in the launcher I get this error:   

--- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 01/09/19 15:05
Description: Initializing game

java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL
	at cuo.b(SourceFile:199)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuo.<init>(SourceFile:81)
	at dnr.a(SourceFile:19)
	at cyc.au(SourceFile:464)
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cuo.b(SourceFile:199)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuo.<init>(SourceFile:81)
	at dnr.a(SourceFile:19)
	at cyc.au(SourceFile:464)

-- Initialization --
Details:
Stacktrace:
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 894615704 bytes (853 MB) / 1560281088 bytes (1488 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: 1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by Fakeowo** [comment]
Your problem is here: "The driver does not appear to support OpenGL".
I can give you option to update your drivers (system, or graphic card, idk.). You can of course google some options on the internet with this sentence:
"java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL".

I hope I was helpful :]
~Fake__

**Comment by javi21** [comment]
A mi me pasa lo mismo que @agus98698 pero los controladores es actualizados y he estado buscando con la frase que mencionaste: "java.lang.IllegalStateException: error 65542 de GLFW: WGL: el controlador no parece admitir OpenGL" y no he encontrado nada útil. Además he probado muchas cosas ya y estoy mosqueado. A ver a mi esto me pasa solo con los launchers pirata pero con el original no me da problema, sin embargo mis colegas no tienen el original y juegan en online con una vpn, pero yo con los launcher pirata tengo el error de este chico.
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 14/09/19 16:25
Description: Initializing game

java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL
	at cuo.b(SourceFile:199)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuo.<init>(SourceFile:81)
	at dnr.a(SourceFile:19)
	at cyc.au(SourceFile:464)
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cuo.b(SourceFile:199)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuo.<init>(SourceFile:81)
	at dnr.a(SourceFile:19)
	at cyc.au(SourceFile:464)

-- Initialization --
Details:
Stacktrace:
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation


El launcher es: Sklauncher 3.0-6ea10ed
Muchas gracias por su  ayuda. XD

**Comment by Fakeowo** [comment]
Hello, your problem is here as well as the person above had: "The driver does not appear to support OpenGL".
The solution is to update your drivers (system, or graphic card, idk.). You can search for other options  on the internet with this sentence:
"java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL".

I hope I was helpful :]
~Fake__
