### ISSUE TITLE
Someone help plss I can't play minecraft

### ISSUE THREAD

**Issue by Gom12** [skmedix/SKlauncher#211]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 10/10/19 3:45 PM
Description: Initializing game

java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL
	at cuo.b(SourceFile:199)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuo.<init>(SourceFile:81)
	at dnr.a(SourceFile:19)
	at cyc.au(SourceFile:464)
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cuo.b(SourceFile:199)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuo.<init>(SourceFile:81)
	at dnr.a(SourceFile:19)
	at cyc.au(SourceFile:464)

-- Initialization --
Details:
Stacktrace:
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 572951912 bytes (546 MB) / 1291845632 bytes (1232 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: 1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by Indexerrowaty** [comment]
Have you been able to play Minecraft before?
And what graphics card do you have?
