### ISSUE TITLE
Nenhum Laucher abre o Minecraft

### ISSUE THREAD

**Issue by atalegal** [skmedix/SKlauncher#213]
Possível problema com o Java, já que os dois Lauchers que eu uso não abrem o jogo

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 24/10/19 19:51
Description: Initializing game

java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL
	at cuo.b(SourceFile:199)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuo.<init>(SourceFile:81)
	at dnr.a(SourceFile:19)
	at cyc.au(SourceFile:464)
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cuo.b(SourceFile:199)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuo.<init>(SourceFile:81)
	at dnr.a(SourceFile:19)
	at cyc.au(SourceFile:464)

-- Initialization --
Details:
Stacktrace:
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 147404512 bytes (140 MB) / 369098752 bytes (352 MB) up to 1073741824 bytes (1024 MB)
	CPUs: 4
	JVM Flags: 10 total; -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx1024m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Launched Version: 1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

 - OS: Windows 10
 - Java Version: Versão 8, atualização 231
 - Launcher Version: beta 3.0-cc57ce3
 - Browser: Chrome

**Comment by TheusKhan** [comment]
He said, "Possible problem with the game as neither launcher opens the game."

Olá amigo, tudo bom? Por aqui falamos somente em inglês. Se possível, continue a relatar no idioma adequado. Obrigado.

**Comment by Indexerrowaty** [comment]
Please update your drivers. If this won't help then unfortunately it's time to upgrade your PC to a newer one.
Here are help articles on how to update drivers on Windows 10.
EN: https://support.microsoft.com/en-us/help/4028443/windows-10-update-drivers
PT: https://support.microsoft.com/pt-pt/help/4028443/windows-10-update-drivers
