### ISSUE TITLE
The game don't want to start

### ISSUE THREAD

**Issue by WoufGudBoi** [skmedix/SKlauncher#215]
When i click on launch it's keep saying launching but minecraft don't want to start
Here is what is written
[09:02:46 ERROR]: Couldn't unpack natives!
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_231]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_231]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_231]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.launcher.game.MinecraftGameRunner.unpackNatives(MinecraftGameRunner.java:421) ~[sklauncher-fx.jar:3.0-cc57ce3]
	at net.minecraft.launcher.game.MinecraftGameRunner.launchGame(MinecraftGameRunner.java:138) ~[sklauncher-fx.jar:3.0-cc57ce3]
	at com.mojang.launcher.game.runner.AbstractGameRunner.onDownloadJobFinished(AbstractGameRunner.java:191) ~[sklauncher-fx.jar:3.0-cc57ce3]
	at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:120) ~[sklauncher-fx.jar:3.0-cc57ce3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

im on Windows 10 and i don't now the java ver but the launcher is in 3.0

**Comment by wojteknieja** [comment]
i have the same ---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 23.11.19 15:24
Description: Initializing game

java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL
	at cuo.b(SourceFile:199)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuo.<init>(SourceFile:81)
	at dnr.a(SourceFile:19)
	at cyc.au(SourceFile:464)
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cuo.b(SourceFile:199)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuo.<init>(SourceFile:81)
	at dnr.a(SourceFile:19)
	at cyc.au(SourceFile:464)

-- Initialization --
Details:
Stacktrace:
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1012289800 bytes (965 MB) / 1291845632 bytes (1232 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 2
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: 1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by Indexerrowaty** [comment]
@wojteknieja Update your drivers.
https://www.lifewire.com/how-to-update-drivers-in-windows-2619214
