### ISSUE TITLE
Launcher fails to start

### ISSUE THREAD

**Issue by hasashin** [skmedix/SKlauncher#216]
Just after connecting to server, Launcher tries to launch, but it fails with log:

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at pl.skmedix.bootstrap.BootstrapController.startLauncher(BootstrapController.java:465)
	at pl.skmedix.bootstrap.BootstrapController.lambda$null$1(BootstrapController.java:74)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseReader(Lcom/google/gson/stream/JsonReader;)Lcom/google/gson/JsonElement;
	at net.minecraft.launcher.LauncherSettings.loadConfig(LauncherSettings.java:144)
	at net.minecraft.launcher.LauncherSettings.<init>(LauncherSettings.java:29)
	at net.minecraft.launcher.Launcher.<init>(Launcher.java:124)
	... 10 more
```

 - OS: MacOS Catalina 10.15.1
 - Java Version: jdk8u231
 - Launcher Version: 3.0-b12

**Comment by skmedix** [comment]
@hasashin Was this error occurring on b11?

**Comment by hasashin** [comment]
@skmedix No, launcher sometimes didn't show up, but worked fine

**Comment by skmedix** [comment]
Okay, I'll revert gson changes and release auto-update in 15mins

**Comment by skmedix** [comment]
Released `3.0-7c274a8`

**Comment by hasashin** [comment]
Now, after downloaded newer build works just fine

**Comment by skmedix** [comment]
Great! Thanks for reporting!
