### ISSUE TITLE
I have a problem with sklauncher because I will still get an error ... I've downloaded and updated 64 bit because I am overwhelmed by the settin Java. I do not know what to dogs on average.  

### ISSUE THREAD

**Issue by dvlcia** [skmedix/SKlauncher#285]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at bib.I(SourceFile:2825)
	at net.minecraft.client.main.Main.main(SourceFile:38)

**Comment by NightFurySL2001** [comment]
Please check  your java edition by going to the Command Promt and type `java -version` and then enter. It should include a "64-bit" in the output.
![image](https://user-images.githubusercontent.com/33471049/81364018-3c4a5080-9117-11ea-9e61-a37fb7d1e014.png)
