### ISSUE TITLE
Po włączeniu gry i wejścia na świat od razu mnie wyrzuca

### ISSUE THREAD

**Issue by Spiker04** [skmedix/SKlauncher#316]
Po włączeniu gry gra bardzo szybko dostaje crusha i dostaje taką informacje:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 30.06.20 10:15
Description: Tesselating block model

java.lang.OutOfMemoryError: Metaspace
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at ecs.b(SourceFile:66)
	at ecs.a(SourceFile:47)
	at ecq.a(SourceFile:61)
	at een$c$b.a(SourceFile:512)
	at een$c$b.a(SourceFile:434)
	at een$c.k(SourceFile:399)
	at een.a(SourceFile:181)
	at ebx.a(SourceFile:955)
	at ebx.a(SourceFile:1107)
	at ebs.a(SourceFile:717)
	at ebs.a(SourceFile:540)
	at dlx.e(SourceFile:1021)
	at dlx.e(SourceFile:654)
	at net.minecraft.client.main.Main.main(SourceFile:215)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at ecs.b(SourceFile:66)

-- Block model being tesselated --
Details:
	Block: Block{minecraft:stone}
	Block location: World: (-224,64,0), Chunk: (at 0,4,0 in -14,0; contains blocks -224,0,0 to -209,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Using AO: true
Stacktrace:
	at ecs.a(SourceFile:47)

-- Block being tesselated --
Details:
	Block: Block{minecraft:stone}
	Block location: World: (-224,64,0), Chunk: (at 0,4,0 in -14,0; contains blocks -224,0,0 to -209,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at ecq.a(SourceFile:61)
	at een$c$b.a(SourceFile:512)
	at een$c$b.a(SourceFile:434)
	at een$c.k(SourceFile:399)
	at een.a(SourceFile:181)
	at ebx.a(SourceFile:955)
	at ebx.a(SourceFile:1107)
	at ebs.a(SourceFile:717)

-- Affected level --
Details:
	All players: 1 total; [ebf['Spiker04'/403, l='ClientLevel', x=-215.50, y=64.00, z=14.50]]
	Chunk stats: Client Chunk Cache: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,63,16), Chunk: (at 0,3,0 in -14,1; contains blocks -224,0,16 to -209,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 21 game time, 21 day time
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at dym.a(SourceFile:449)
	at dlx.c(SourceFile:2181)
	at dlx.e(SourceFile:672)
	at net.minecraft.client.main.Main.main(SourceFile:215)

-- System Details --
Details:
	Minecraft Version: 1.16
	Minecraft Version ID: 1.16
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 551724392 bytes (526 MB) / 855638016 bytes (816 MB) up to 1073741824 bytes (1024 MB)
	CPUs: 8
	JVM Flags: 10 total; -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx1024m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Launched Version: 1.16
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.45, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz

**Comment by Indexerrowaty** [comment]
Problem rozwiązany na [serwerze SKlaunchera](https://discord.gg/BdCcpDZ)
