### ISSUE TITLE
Minecraft crashes when I put mods

### ISSUE THREAD

**Issue by Roalruez** [skmedix/SKlauncher#323]
Hello good afternoon, I would like to know how to solve this problem, at the time of putting mods in the folder mods and start the game does not open it, I think it crashes, the truth is I can not understand what it is.

[18:11:22] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:11:22] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:11:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[18:11:22] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[18:11:22] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_251, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_251
[18:11:23] [main/INFO] [FML]: Searching C:\Users\aleja\AppData\Roaming\.minecraft\mods for mods
[18:11:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in future-mc-1.12.2-0.2.3.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:11:23] [main/WARN] [FML]: The coremod FutureMC (thedarkcolour.futuremc.asm.CoreLoader) is not signed!
[18:11:23] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_F5.jar
[18:11:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:11:23] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[18:11:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:11:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:11:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:11:23] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[18:11:23] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[18:11:23] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[18:11:23] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[18:11:23] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: C:\Users\aleja\AppData\Roaming\.minecraft\mods\OptiFine_1.12.2_HD_U_F5.jar
[18:11:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:11:26] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[18:11:27] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[18:11:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:11:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:11:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:11:27] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[18:11:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[18:11:27] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[18:11:27] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[18:11:29] [Client thread/INFO] [minecraft/Minecraft]: Setting user: Elseys
[18:11:31] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/gen/feature/WorldGenBigTree
	at net.minecraft.block.Block.func_149671_p(Block.java:2347) ~[aow.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.gen.feature.WorldGenBigTree
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.block.Block.func_149671_p(Block.java:2347) ~[aow.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer thedarkcolour.futuremc.asm.CoreTransformer@3b4a1a75 from coremod FutureMC
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.block.Block.func_149671_p(Block.java:2347) ~[aow.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: kotlin/jvm/functions/Function1
	at thedarkcolour.futuremc.asm.CoreTransformer.findMethod(CoreTransformer.java:171) ~[future-mc-1.12.2-0.2.3.2.jar:?]
	at thedarkcolour.futuremc.asm.CoreTransformer.patchWorldGenBigTree(CoreTransformer.java:98) ~[future-mc-1.12.2-0.2.3.2.jar:?]
	at thedarkcolour.futuremc.asm.CoreTransformer.transform(CoreTransformer.java:36) ~[future-mc-1.12.2-0.2.3.2.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.block.Block.func_149671_p(Block.java:2347) ~[aow.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NoClassDefFoundError: kotlin/jvm/functions/Function1
	at thedarkcolour.futuremc.asm.CoreTransformer.findMethod(CoreTransformer.java:171) ~[future-mc-1.12.2-0.2.3.2.jar:?]
	at thedarkcolour.futuremc.asm.CoreTransformer.patchWorldGenBigTree(CoreTransformer.java:98) ~[future-mc-1.12.2-0.2.3.2.jar:?]
	at thedarkcolour.futuremc.asm.CoreTransformer.transform(CoreTransformer.java:36) ~[future-mc-1.12.2-0.2.3.2.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.block.Block.func_149671_p(Block.java:2347) ~[aow.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.functions.Function1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at thedarkcolour.futuremc.asm.CoreTransformer.findMethod(CoreTransformer.java:171) ~[future-mc-1.12.2-0.2.3.2.jar:?]
	at thedarkcolour.futuremc.asm.CoreTransformer.patchWorldGenBigTree(CoreTransformer.java:98) ~[future-mc-1.12.2-0.2.3.2.jar:?]
	at thedarkcolour.futuremc.asm.CoreTransformer.transform(CoreTransformer.java:36) ~[future-mc-1.12.2-0.2.3.2.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.block.Block.func_149671_p(Block.java:2347) ~[aow.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at thedarkcolour.futuremc.asm.CoreTransformer.findMethod(CoreTransformer.java:171) ~[future-mc-1.12.2-0.2.3.2.jar:?]
	at thedarkcolour.futuremc.asm.CoreTransformer.patchWorldGenBigTree(CoreTransformer.java:98) ~[future-mc-1.12.2-0.2.3.2.jar:?]
	at thedarkcolour.futuremc.asm.CoreTransformer.transform(CoreTransformer.java:36) ~[future-mc-1.12.2-0.2.3.2.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.block.Block.func_149671_p(Block.java:2347) ~[aow.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Exception in thread "Client thread" [18:11:31] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[18:11:31] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[18:11:31] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[18:11:31] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[18:11:31] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[18:11:31] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[18:11:31] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:

**Comment by Linkshu1** [comment]
i have the same problem too

**Comment by Indexerrowaty** [comment]
Try removing FutureMC mod and try again

**Comment by Roalruez** [comment]
If you took the mod out of the mods folder if you open it, but I want to play with that mod. Plus I always get that error with any other mod.

**Comment by Roalruez** [comment]
From what little I've understood it might be a mistake of the FMLCore, because I already tried to install Java 7, because before the upgrade to Java 8 the Minecraft allowed me to play with MODs, but I already discarded that possibility.
