### ISSUE TITLE
sklauncher no abre minecraft

### ISSUE THREAD

**Issue by TMS-vdfh** [skmedix/SKlauncher#365]
**Describe the bug**
sklauncher no me deja abrir minecraft

**To Reproduce**
1. abrir sklauncher
2. iniciar minecraft
3. version 1.16 forge 35.0.18

**Expected behavior**

**Screenshots**

**If the bug is launcher related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Ubuntu 17.10]
 - Java Version: [e.g. 8u181]
 - Launcher Version: [e.g. 2.8.0_40, 3.0-4c2b0e6]

**If the bug is website related:**
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, Android 8.1]
 - Browser: [e.g. Chrome 68, Firefox 61.0.1]

**Comment by Indexerrowaty** [comment]
Please send launcher log or Minecraft crashlog if it shows up.

**Comment by TMS-vdfh** [comment]
![image](https://user-images.githubusercontent.com/75279381/100671800-d554e900-333f-11eb-9a37-73123391eb49.png)

**Comment by Indexerrowaty** [comment]
Can you please copy Game Output and paste it here? Thanks.

**Comment by TMS-vdfh** [comment]
2020-12-01 15:05:34,775 main WARN Advanced terminal features are not available in this environment
[15:05:35] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, TMSvdfh, --version, 1.16.4-forge-35.0.18, --gameDir, C:\Users\TomyMate\AppData\Roaming\.minecraft, --assetsDir, C:\Users\TomyMate\AppData\Roaming\.minecraft\assets, --assetIndex, 1.16, --uuid, a41bfc6726bd388d9c3f21e5caa8a599, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 854, --height, 480, --launchTarget, fmlclient, --fml.forgeVersion, 35.0.18, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201102.104115]
[15:05:35] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.6+85+master.325de55 starting: java version 1.8.0_251 by Oracle Corporation
[15:05:35] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[15:05:35] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\TomyMate\AppData\Roaming\.minecraft\mods\OptiFine_1.16.4_HD_U_G5.jar
[15:05:35] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[15:05:35] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[15:05:35] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/TomyMate/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[15:05:35] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
Exception in thread "main" [15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: Failed to load FML config from C:\Users\TomyMate\AppData\Roaming\.minecraft\config\fml.toml
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLConfig.loadFrom(FMLConfig.java:64)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLConfig.load(FMLConfig.java:77)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:81)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.HashMap$Values.forEach(Unknown Source)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.core.file.AutoreloadFileConfig.load(AutoreloadFileConfig.java:41)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLConfig.loadFrom(FMLConfig.java:60)
[15:05:35] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 9 more

**Comment by Indexerrowaty** [comment]
Delete this `fml.toml` that's located here: `%AppData%\Roaming\.minecraft\config\fml.toml`.
Sorry for late response.
